
// File generated by FlutLab.
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for iOS - '
          'try to add using FlutLab Firebase Configuration',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'it not supported by FlutLab yet, but you can add it manually',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'it not supported by FlutLab yet, but you can add it manually',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'it not supported by FlutLab yet, but you can add it manually',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBnduGpu8CujDznZV-dnZ5upwZnsySRkzE',
    authDomain: 'mayproj-5597a.firebaseapp.com',
    projectId: 'mayproj-5597a',
    storageBucket: 'mayproj-5597a.appspot.com',
    messagingSenderId: '1032306102428',
    appId: '1:1032306102428:web:1896bb66c6ff9db1f9dd59',
    measurementId: 'G-RD4SQHZMML'
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCqQLmlAb7g3ldPOBwZcZxBQn_iWvDCU-s',
    appId: '1:823442688654:android:3442732246e9016a8bd7df',
    messagingSenderId: '823442688654',
    projectId: 'test11-2ad73',
    storageBucket: 'test11-2ad73.appspot.com'
  );
}
